sudo: required
services:
  - docker
before_install:
  - docker build -t veeraarad/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true veeraarad/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-1-480263221770"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
